packages:
  - 'packages/*'
  - 'packages/web/backend'
  - 'packages/web/common'
  - 'packages/web/frontend'
  - 'packages/desktop/windows'
  - 'packages/desktop/mac'
  - 'packages/desktop/linux'
  - 'packages/mobile/android'
  - 'packages/mobile/ios'